[workspace]
members = [
    "contracts/pricefeed",
    "contracts/core/vault-pricefeed",

    "contracts/core/vault-storage",
    "contracts/core/vault-utils",
    "contracts/core/vault",

    "contracts/core/shorts-tracker",
    "contracts/core/rlp-manager",

    "contracts/referrals/referral-storage",
    "contracts/referrals/referral-reader",

    "contracts/assets/yield-tracker",
    "contracts/assets/yield-asset",
    "contracts/assets/rusd",
    "contracts/assets/rlp",
    "contracts/assets/rsct",
]
