[workspace]
members = [
    # "contracts/fungible",
    # "contracts/pricefeed",
    # "contracts/core/vault-pricefeed",

    # "contracts/core/vault-storage",
    # "contracts/core/vault-utils",
    "contracts/core/vault",

    # "contracts/assets/yield-tracker",
    # "contracts/assets/yield-asset",
    # "contracts/assets/rusd",
    # "contracts/assets/time-distributor",
    # "contracts/assets/rlp",

    # "contracts/utils",
]
