[workspace]
members = [
    "contracts/pricefeed",
    "contracts/core/vault-pricefeed",

    "contracts/core/vault-storage",
    "contracts/core/vault-utils",
    "contracts/core/vault",

    "contracts/assets/time-distributor",
    "contracts/assets/yield-tracker",
    "contracts/assets/rusd",
]
