[workspace]
members = [
    "contracts/fungible",

    "contracts/wrapped-asset",
    "contracts/pricefeed",
    "contracts/core/vault-pricefeed",

    "contracts/core/vault-storage",
    "contracts/core/vault-utils",
    "contracts/core/vault",

    "contracts/core/router",
    "contracts/core/shorts-tracker",
    "contracts/core/base-position-manager",
    "contracts/core/permissioned-position-router",
    "contracts/core/position-router",
    "contracts/core/position-manager",
    "contracts/core/orderbook",
    "contracts/core/rlp-manager",

    "contracts/peripherals/reader",
    "contracts/peripherals/balance-updater",
    "contracts/peripherals/vault-reader",
    "contracts/peripherals/orderbook-reader",

    "contracts/referrals/referral-storage",
    "contracts/referrals/referral-reader",

    "contracts/assets/yield-tracker",
    "contracts/assets/yield-asset",
    "contracts/assets/rusd",
    "contracts/assets/time-distributor",
    "contracts/assets/rlp",
    "contracts/assets/rsct",

    "contracts/utils",

    #
    ############# Scripts #############
    #
    # "scripts/transfer-assets-to-contract",
    # "scripts/position-router-increase",
    # "scripts/encode-mock-price-data",
    # "scripts/decode-mock-price-data",

    # Testable contracts (for internal testing)
    # "contracts/testable/hash",
    # "contracts/testable/bytes-conversion",
    # "contracts/testable/transfer",
    # "contracts/testable/numeric",
    # "contracts/testable/storage",
    # "contracts/testable/signed_64",
    # "contracts/testable/signed_256",
    # "contracts/testable/dummy",
    # "contracts/testable/balance-checker",
    # "contracts/testable/tester",
    # "contracts/testable/wrapped-asset-dummy",
    # "contracts/testable/native-asset",
    # "contracts/testable/external-call/callee",
    # "contracts/testable/external-call/caller",
]
