[project]
authors = ["Burra Labs @theausicist", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "permissioned-position-router"

[dependencies]
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
