[project]
authors = ["Burra Labs @theausicist", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "decode-mock-price-data"

[dependencies]
helpers = { path = "../../contracts/helpers" }
core_interfaces = { path = "../../contracts/core/interfaces" }