[project]
authors = ["Burra Labs @theausicist", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "pricefeed"

[dependencies]
helpers = { path = "../helpers" }
interfaces = { path = "../interfaces" }