[project]
authors = ["Burra Labs @theausicist", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "orderbook_reader"

[dependencies]
helpers = { path = "../../helpers" }
interfaces = { path = "../../interfaces" }
core_interfaces = { path = "../../core/interfaces" }
peripheral_interfaces = { path = "../interfaces" }
