[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "lib.sw"
license = "Apache-2.0"
name = "core_interfaces"

[dependencies]
helpers = { path = "../../helpers" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain" }