[project]
authors = ["Burra Labs @theausicist", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "referral-reader"

[dependencies]
helpers = { path = "../../helpers" }
referrals_interfaces = { path = "../interfaces" }
