[project]
authors = ["Burra Labs @theausicist", "@xburralabs"]
entry = "main.sw"
license = "Apache 2.0"
name = "yield-tracker"

[dependencies]
asset_interfaces = { path = "../interfaces" }
helpers = { path = "../../helpers" }
